apiVersion: argoproj.io/v1alpha1 
kind: ApplicationSet
metadata:
  name: gocalsy-apps
  namespace: openshift-gitops 
spec:
  generators: 
  - list:
      elements:
      - cluster: dev
        url: https://kubernetes.default.svc
        namespace: gocalsy-dev
        targetRevision: HEAD
        imageTag: "latest"
        followChangesForBranch: "main"
      # - cluster: stage
      #   url: https://kubernetes.default.svc
      #   namespace: gocalsy-stage
      #   targetRevision: HEAD
      #   imageTag: "Release-1.0.2"
      #   followChangesForBranch: "Release-1.0" # build when startsWith
      # - cluster: prod
      #   url: https://kubernetes.default.svc
      #   namespace: gocalsy-prod
      #   imageTag: "Release-1.0.0"
      #   targetRevision: HEAD
      #   followChangesForBranch: "" # -> empty means don't follow
  template:
    metadata:
      name: 'gocalsy-{{cluster}}-app'
    spec:
      project: default 
      source:
        repoURL: "https://github.com/gmodzelewski/google-cal-sync-manifests"
        targetRevision: '{{targetRevision}}'
        path: gocalsy
        helm:
          # valueFiles: 
          # - values.{{cluster}}.yaml
          parameters:
          # - name: manifestsGitRepo
          #   value: 'https://github.com/gmodzelewski/google-cal-sync-manifests'
          # - name: gitRepo
          #   value: 'https://github.com/gmodzelewski/google-cal-sync'
          # - name: image.repository
          #   value: 'quay.io/modzelewski/quinoa-wind-turbine'
          - name: image.tag
            value: '{{imageTag}}'
          - name: followChangesForBranch
            value: '{{followChangesForBranch}}'
      destination:
        server: '{{url}}' 
        namespace: '{{namespace}}'
      syncPolicy: 
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true
      ignoreDifferences:
      - group: image.openshift.io
        kind: ImageStream
        jsonPointers:
        - /spec/tags
      - group: apps.openshift.io
        kind: DeploymentConfig
        jsonPointers:
        - /spec/template/spec/containers/0/image