{{- if .Values.followChangesForBranch }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/managed-by: EventListener
    app.kubernetes.io/part-of: Triggers
    eventlistener: {{ include "gocalsy.fullname" . }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  name: eventlistener-{{ include "gocalsy.fullname" . }}
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: el-{{ include "gocalsy.fullname" . }}
    weight: 100
{{- end }}