{{- if .Values.followChangesForBranch }}
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: {{ include "gocalsy.fullname" . }}-pipeline
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  params:
  - name: GIT_REVISION
    type: string
  - default: {{ .Values.gitRepo }}
    name: GIT_REPO
    type: string
  - default: "empty"
    name: GIT_COMMIT_MESSAGE
    type: string
  - default: {{ coalesce .Values.image.tag "latest" }}
    name: IMAGE_TAG
    type: string
  - default: {{ coalesce .Values.image.repository "quay.io/modzelewski/gocalsy" }}
    name: IMAGE_NAME
    type: string
  tasks:
  - name: git-clone
    params:
    - name: url
      value: $(params.GIT_REPO)
    - name: revision
      value: $(params.GIT_REVISION)
    - name: submodules
      value: "true"
    - name: depth
      value: "1"
    - name: sslVerify
      value: "true"
    - name: crtFileName
      value: ca-bundle.crt
    - name: deleteExisting
      value: "true"
    - name: verbose
      value: "true"
    - name: gitInitImage
      value: registry.redhat.io/openshift-pipelines/pipelines-git-init-rhel8@sha256:cadf614a6044ee37397de3abe7674827ecab225e7fac9fb123eff5473e2c4003
    - name: userHome
      value: /tekton/home
    taskRef:
      kind: ClusterTask
      name: git-clone
    workspaces:
    - name: output
      workspace: source
  - name: maven
    params:
    - name: MAVEN_IMAGE
      value: quay.io/rhdevelopers/maven-nodejs:latest
    - name: GOALS
      value:
      - package
    - name: PROXY_PROTOCOL
      value: http
    - name: CONTEXT_DIR
      value: .
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: maven
    workspaces:
    - name: maven-settings
      workspace: maven-settings
    - name: source
      workspace: source
  - name: buildah
    params:
    - name: IMAGE
      value: $(params.IMAGE_NAME):$(params.IMAGE_TAG)
    - name: BUILDER_IMAGE
      value: registry.redhat.io/rhel8/buildah@sha256:0a86ecbdfbe86e9d225b7fe4b090a0dd6d323f8afdfdf2bd933ff223ddb53320
    - name: STORAGE_DRIVER
      value: vfs
    - name: DOCKERFILE
      value: {{ .Values.containerfilePath }}
    - name: CONTEXT
      value: .
    - name: TLSVERIFY
      value: "true"
    - name: FORMAT
      value: oci
    - name: SKIP_PUSH
      value: "false"
    runAfter:
    - maven
    taskRef:
      kind: ClusterTask
      name: buildah
    workspaces:
    - name: source
      workspace: source
  finally:
    - name: rollout
      params:
        - name: SCRIPT
          value: |
            echo "Showing some more infos for debugging reasons:"

            echo "Build image from git commit with message: $(params.GIT_COMMIT_MESSAGE)"

            echo "Trying to tag image quinoa-wind-turbine:$(params.IMAGE_TAG) to:"

            echo "$(tasks.buildah.results.IMAGE_DIGEST)"

            oc tag $(params.IMAGE_NAME)@$(tasks.buildah.results.IMAGE_DIGEST) quinoa-wind-turbine:$(params.IMAGE_TAG)
            
            oc rollout latest dc/quinoa-wind-turbine || true 
        - name: VERSION
          value: latest
      taskRef:
        kind: ClusterTask
        name: openshift-client
  workspaces:
  - name: source
  - name: maven-settings
{{- end }}